<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.keystone</groupId>
        <artifactId>keystone-root</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>keystone-admin</artifactId>
    <packaging>jar</packaging>
    <description>Keystone Web 启动入口 - Controller 路由分发、接口文档暴露</description>

    <dependencies>
        <!-- 内部模块 -->
        <dependency>
            <groupId>com.keystone</groupId>
            <artifactId>keystone-system</artifactId>
        </dependency>
        <dependency>
            <groupId>com.keystone</groupId>
            <artifactId>keystone-ai</artifactId>
        </dependency>
        <dependency>
            <groupId>com.keystone</groupId>
            <artifactId>keystone-generator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>3.0.2</version>
        </dependency>


        <!-- Spring Boot Test -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
