<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.keystone</groupId>
        <artifactId>keystone-root</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>keystone-system</artifactId>
    <packaging>jar</packaging>
    <description>Keystone 基础系统 - RBAC 用户、角色、菜单、字典、部门管理</description>

    <dependencies>
        <dependency>
            <groupId>com.keystone</groupId>
            <artifactId>keystone-framework</artifactId>
        </dependency>
    </dependencies>

</project>
